skip_tags: true

configuration: Release

before_build:
  - nuget restore src\Pirac.sln

cache:
  - src\packages -> **\packages.config

build:
  parallel: true
  project: src\Pirac.sln

test:
  assemblies:
    - src\Pirac.Tests\bin\Release\Pirac.Tests.dll

artifacts:
  - path: src\artifacts\*.nupkg