configuration: Release

os: Visual Studio 2015 CTP

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - nuget restore src\Pirac.sln

build:
  parallel: true

artifacts:
  - path: src\Pirac\bin\Release\*.nupkg